[tool.poetry]
name = "op-core"
version = "0.1.0"
description = ""
authors = ["Jos√© Ribeiro <me@joseribeiro.dev>"]

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
